### PR TITLE
Add home from real world cracked pw

### PR DESCRIPTION
**Pull request by ukscone**
Add home from real world cracked pw

MySpectrumWiFi45-2G, royalhome606

### CODE REVIEW

**Comment by Ntrain2k** [comment]
I think home is already on there.

**Comment by ukscone** [comment]
i don't see it in words.txt or netgear-spectrum.txt

**Comment by Ntrain2k** [comment]
Look in noun_large.txt    

It isn't in the smaller dictionaries but is available in the full list.

**Comment by ukscone** [comment]
ok null problemo

**Comment by soxrok2212** [comment]
Please feel free to re-open this. If the work is new to words.txt, then it’s a certain used word. 

After that, remove netgear-spectrum.txt and use the combine script to re-create it with the new word(s). 

Thanks!

**Pull request closed without merging**
