### PR TITLE
Moved words to correct files and added new words

### PR DESCRIPTION
**Pull request by turbozapekanka**

### CODE REVIEW

**Comment by soxrok2212** [comment]
The story with this is Spectrum (ISP) has a spin-off of NETGEAR’s adj-noun and those were found on eBay stickers. I supposed it’d be a good idea to just create a Spectrum-specific list.

**Comment by turbozapekanka** [comment]
are you saying anchor/engine/input/leader are used in place of adjective on these routers? what's the noun for these words then?

**Comment by soxrok2212** [comment]
That’s correct. For example, on an sBay sticker I found “wagongallon153”... noun+noun.

**Comment by turbozapekanka** [comment]
I see, I would keep these together with netgear, maybe add a note about noun+noun combinations.

**Comment by turbozapekanka** [comment]
Unless there is a reliable way to distinguish Spectrum noun+noun models from Netgear adj+noun.

**Pull request closed without merging**
